### ISSUE TITLE
Raw MIDI output

### ISSUE THREAD

**Issue by baconpaul** [free-audio/clap-wrapper#105]
In #104 I added output ports for CLAP_EVENT_NOTE_BLAH

but I just made midi events fprintf stderr for now

We need to fix that.

**Comment by baconpaul** [comment]
removed the solved in next from this; the CLAP_NOTE ones work in next but the MIDI ones dont yet

**Comment by baconpaul** [comment]
Note to self: we also want to send CLAP_NOTE_EXPRESSIONS out.

**Comment by defiantnerd** [comment]
Since initial version is complete, for CLAP_NOTE_EXPRESSIONS we can open a new issue.
Notes, Program Changes and simple controllers are being sent.
