### ISSUE TITLE
VST3 Parameter Menu support

### ISSUE THREAD

**Issue by baconpaul** [free-audio/clap-wrapper#117]
Both VST3 and CLAP have parameter menu support, clap through an extension and vST3 through an iInterface

We should bridge these. It is a very useful property of VST3

Surge XT exercises this in both APIs today.

Not urgent, but before 1.0

**Comment by defiantnerd** [comment]
solved in branch `next`

**Comment by defiantnerd** [comment]
available in 0.9.0
