### ISSUE TITLE
pass VST3 verification for FL Studio

### ISSUE THREAD

**Issue by 0ax1** [free-audio/clap-wrapper#149]
as of now, the VST3 wrapper does not pass the VST3 plugin verification in FL Studio. in addition, the user needs to set the plugin type `Synth/Effect` manually in FL, in order for the plugin to open.

**Comment by defiantnerd** [comment]
I have Apricot and Surge through the wrapper validating in FL Studio, but not clap-saw-studio.

This is somehow connected to the plugin it seems.

**Comment by 0ax1** [comment]
Aha, probably there's just one small tweak missing somewhere to make this work.

**Comment by defiantnerd** [comment]
I've contacted Image-Line for a developer contact. Let's see.

**Comment by 0ax1** [comment]
> I've contacted Image-Line for a developer contact. Let's see.

I actually also pinged them on their forum, with the response that they didn't manage to narrow down the problem on their end ad-hoc.

**Comment by 0ax1** [comment]
Same happens by the way when loading the `AudioPluginDemo_VST3` example project from JUCE.

**Comment by defiantnerd** [comment]
Actually they don't need to narrow down anything - just tell where they keep the logs of the scan process.

**Comment by 0ax1** [comment]
> Actually they don't need to narrow down anything - just tell where they keep the logs of the scan process.

Their own logs didn't reveal anything.

**Comment by 0ax1** [comment]
Probably the same amount of info we get from the logs aka. nothing.

**Comment by defiantnerd** [comment]
It works now in FL Studio as VST3 and AUv2.

**Comment by defiantnerd** [comment]
Merged to 0.6.0
