### ISSUE TITLE
optimize lock-free queue

### ISSUE THREAD

**Issue by 0ax1** [free-audio/clap-wrapper#150]
our current lock-free queue uses the modulo `%` operator which is computationally expensive. whilst compilers as part of optimization can replace `%` with a bitwise `&` for queue sizes which are a multiple of 2, we shouldn't rely on the compiler to do this optimization but use a bitwise `&` explicitly.

**Comment by 0ax1** [comment]
addressed in: https://github.com/free-audio/clap-wrapper/pull/154

**Comment by defiantnerd** [comment]
Merged to 0.6.0
