### ISSUE TITLE
AUv2 release build fails 

### ISSUE THREAD

**Issue by u-he-frank** [free-audio/clap-wrapper#227]
https://github.com/free-audio/clap-wrapper/blob/3ea56d943b157fd61bd6c4f0dedb477951d66b31/src/wrapasauv2.cpp#L955-L956

assert is not working in release builds and therefore line 955 produces an undefined variable. With llvm options [-Werror,-Wunused-variable] the release build fails.

**Comment by baconpaul** [comment]
Thanks for the fix in #228
