### ISSUE TITLE
Werror and other flags are publicly included in wrappers

### ISSUE THREAD

**Issue by mtytel** [free-audio/clap-wrapper#254]
So if you have warnings in a file included in your Clap plugin code it won't compile.

For VST3 the compile-options could be made PRIVATE
https://github.com/free-audio/clap-wrapper/blob/eb8b1901defd9588fa4a5e66edb0d4c302760ff2/cmake/wrap_vst3.cmake#L87

AU is an interface so not sure if you would just disable those.

**Comment by baconpaul** [comment]
Sorry that was a remnant of when we wanted no warnings in the entire test suite but you are right we should t impose that on everyone.

**Comment by baconpaul** [comment]
i put this on my list to fix early this week. sorry bout that matt! Will ping here when i get it cleaned up.

**Comment by mtytel** [comment]
No worries, i can just have a local fix until it's fixed upstream.
