### ISSUE TITLE
AUv2 without UI crashes validation

### ISSUE THREAD

**Issue by baconpaul** [free-audio/clap-wrapper#257]
The clap-embedded distortion i'm about to add doesn't work ask a AUv2

when validating you get

```
VERIFYING CUSTOM UI
[clap-wrapper] Property: kAudioUnitProperty_CocoaUI plugin
zsh: segmentation fault  auval -v aufx W_pO FrAU
```

so we need to handle the 'doesn't support gui' case in the wrapper

**Comment by defiantnerd** [comment]
fixed in next
