### ISSUE TITLE
Don't statically link MSVC runtime

### ISSUE THREAD

**Issue by mtytel** [free-audio/clap-wrapper#267]
https://github.com/free-audio/clap-wrapper/blob/497f40a7580a2f6326fa06691f39aa3d7e0e78a7/CMakeLists.txt#L29

Should just take the default or whatever the plugin developer set it to.

**Comment by defiantnerd** [comment]
We can make this optional - if the wrapper project is the top level project, the library can be statically linked, otherwise just don't?

**Comment by baconpaul** [comment]
yeah that's what we need to do. i just need to figure out the best way to do that cmakewise. i'll get it this weekend.

**Comment by baconpaul** [comment]
Addressed in [48861ec](https://github.com/free-audio/clap-wrapper/commit/48861ecf472fe2cbcd67478e3f5f0dabe9e5785c)
