### ISSUE TITLE
Wrapped plugins appear as folders instead of packages on Mac

### ISSUE THREAD

**Issue by tas-from-planet-u-he** [free-audio/clap-wrapper#28]
Tested on macOS Monterey 12.6.1 with a 2020 M1 Silicon MacBook Pro.

Merely a cosmetic thing, the wrapped plugin is a regular folder, as opposed to real VST3 plugins, which are some kind of "package" on macOS.

Is it possible to build the wrapped plugin so it appears as a package?

![packagevsfolder](https://user-images.githubusercontent.com/107404067/202220082-e654bcb8-5d7b-4341-997e-0a3c03c605b9.png)

**Comment by defiantnerd** [comment]
Do you know which `SMTG_` switch I need to set that the VST3 SDK builds packages instead of bundles?

**Comment by baconpaul** [comment]
The manual fix to this is to do a `SetFile -a B foo.vst3` but I still haven't figured out why the VST3 SDK doesn't do that for us.

**Comment by baconpaul** [comment]
oh and it is not just cosmetic. While Bitwig will load the folder version, Cubase, Dorico and Reaper will not it seems.

**Comment by baconpaul** [comment]
As @defiantnerd found out, this occurs if you use cmake with a generator other than Xcode. So if you just rebuild with `-G Xcode` it should all be fine.
