### ISSUE TITLE
CLAP_PARAM_IS_STEPPED parameter is not working properly

### ISSUE THREAD

**Issue by lewloiwc** [free-audio/clap-wrapper#300]
When I make this (https://github.com/baconpaul/clap-c99-distortion) into a VST3 using the method described in Getting Started, parameters with CLAP_PARAM_IS_STEPPED don't work properly.
Reaper → https://youtu.be/EfBnUljIXgg
Bitwig → https://youtu.be/cVVahhtgy9o
Live → https://youtu.be/S-7ci_UcmuE

In the CLAP I'm creating, parameters with CLAP_PARAM_IS_STEPPED also don't work properly, so I think it might be an issue with clap-wrapper. Can you reproduce this in your environment?

I'm using Windows 10, and for building, I'm using:
Developer Command Prompt for VS 2022
Visual Studio 2022 Developer Command Prompt v17.10.5

**Comment by defiantnerd** [comment]
You are right. Thanks for bringing this up.

You can fix this by changing line 121 in src/detail/vst3/parameter.cpp from:
`auto param_range = (info->max_value - info->min_value);`
to 
`auto param_range = (info->max_value - info->min_value) + 1`;

I will fix this asap in the `next` branch.

**Comment by defiantnerd** [comment]
it seems that it is an issue with the value string, the parameter itself is working well (you can hear the three different settings).
I'll check it out if I can reproduce that.

**Comment by defiantnerd** [comment]
I am able to reproduce it and this is the fix:
```diff
--- a/src/detail/vst3/parameter.h
+++ b/src/detail/vst3/parameter.h
@@ -54,7 +54,7 @@ class Vst3Parameter : public Steinberg::Vst::Parameter
   {
     if (info.stepCount > 0)
     {
-      return (vst3value * info.stepCount + 1) + min_value;
+      return (vst3value * info.stepCount) + min_value;
     }
     return (vst3value * (max_value - min_value)) + min_value;
   }
```
I'll prepare a fix for the wrapper, too.
