### ISSUE TITLE
Cannot set AUv2 plugin display name to something other than the OUTPUT_NAME parameter.

### ISSUE THREAD

**Issue by directmusic** [free-audio/clap-wrapper#302]
Hello, 

Would there be opposition to having a PRODUCT_NAME or PLUGIN_NAME argument added to target_add_auv2_wrapper() that sets the AudioComponents / name field in the Info.plist without affecting the output file name?

VST3 & CLAP seem to read the title of the plugin from the `clap_plugin_descriptor`'s `name` field which works great for my usecase. However, I plan to have a colon and space in the title of my future plugin such like "PluginTitle: Module". I cannot create a file on macOS with a colon in the filename.

**Comment by directmusic** [comment]
Never mind. After some experimentation I discovered that AUv2 does not seem to like a colon in the name regardless. Closing this.

**Comment by baconpaul** [comment]
Yeah AUv2 uses ":" in the info plist name to separate the manufacturer from the plugin name.
