### ISSUE TITLE
AUv2: Crash when quickly loading multiple copies on M1/M3 Mac

### ISSUE THREAD

**Issue by directmusic** [free-audio/clap-wrapper#304]
Hello, I have been doing some stress testing for the plugins I am working on and noticed that in Live 12.0.1 (as well as 12.1b2) on my M1 MacBook after around the 4th instance of the AUv2 being inserted Live would crash. Initially, it appeared like it was crashing in my GUI, so I disabled "Auto-Open Plug-In Windows" in Live's settings. When attaching Xcode to live it crashes on this line:

https://github.com/free-audio/clap-wrapper/blob/e82e4d7628fe962a3df4bbecff0120bee7d39c31/src/detail/auv2/auv2_base_classes.h#L456

Here is the partial stacktrace:
```
MainThread (1) Queue : com.apple.main-thread (serial)
#0	0x000000018206c14c in CF_IS_OBJC ()
#1	0x0000000181f23dd8 in CFStringGetCString ()
#2	0x000000034cfe47e8 in free_audio::auv2_wrapper::WrapAsAUV2::host_get_name() at /Users/joe/Documents/GitHub/MiniMeters/build/_deps/clap-wrapper-src/src/detail/auv2/auv2_base_classes.h:456
#3	0x000000034dafce3c in Clap::Plugin::Plugin(Clap::IHost*) at /Users/joe/Documents/GitHub/MiniMeters/build/_deps/clap-wrapper-src/src/clap_proxy.cpp:175
#4	0x000000034dafc92c in Clap::Plugin::Plugin(Clap::IHost*) at /Users/joe/Documents/GitHub/MiniMeters/build/_deps/clap-wrapper-src/src/clap_proxy.cpp:184
#5	0x000000034dafc81c in Clap::Plugin::createInstance(clap_plugin_factory const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, Clap::IHost*) at /Users/joe/Documents/GitHub/MiniMeters/build/_deps/clap-wrapper-src/src/clap_proxy.cpp:142
#6	0x000000034cfde410 in free_audio::auv2_wrapper::WrapAsAUV2::WrapAsAUV2(AUV2_Type, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int, ComponentInstanceRecord*) at /Users/joe/Documents/GitHub/MiniMeters/build/_deps/clap-wrapper-src/src/wrapasauv2.cpp:135
```

Additionally this shows up:
```
Application Specific Information:
CF objects must have a non-zero isa
```
When googling that string I found this thread that may explain that this occurs on macOS 14 due to the fact they "added extra hardening to Core Foundation in macOS 14": https://forums.developer.apple.com/forums/thread/739355

I revisited the crash in my GUI code and - while I definitely have a bug there - the stacktrace similarly ends with CFStringGetCString() while macOS tries to generate the crash report inside "com.apple.metal.telemetry".

I can reproduce this in Reaper, Hosting AU, FL Studio 2024 but I have not been able to reproduce this in Logic.
Returning `_hostname.c_str()` at the beginning of the `get_host_name()` stops the crashes.

I can also reproduce this crash using the ClapFirstDistortion Test plugin and it crashes on the same line, or in the call at auv2_base_classes.h:437.

**Reproduction steps:**
* Set Live to not "Auto-Open Plug-In Windows" -- for consistency's sake.
* Build the test plugin and move to the correct folder
* Add an instance in Live
* Duplicate instance as quickly as possible.

It seems like this may be an issue with Audio Units as a whole, but I am not sure. I was unable to make my JUCE plugin crash the same way. However I noticed some other discussions:
https://discussions.apple.com/thread/254500745?sortBy=rank
https://community.native-instruments.com/discussion/19674/logic-crashes-when-loading-certain-libraries-in-kontakt-7

So far my tests included:
* M1 Max MacBook Pro - macOS 14.6.1 - Crash
* M3 Pro MacBook Pro (a friend's machine) - macOS 14.6.1 - Crash

The commands I used to build the project.
```
cmake .. -DCLAP_WRAPPER_DOWNLOAD_DEPENDENCIES=1 -DCLAP_WRAPPER_BUILD_TESTS=1
make
```

**Possible workarounds:**

1. One thing that did work was making all of the `CFStringRef` and the `CFBundleRef` static inside the `get_host_name()` method and not calling `CFRelease()` on any of them. I never had a crash the first load. There must be some edge case inside of CoreFoundation where calling `CFBundleGetValueForInfoDictionaryKey()` fails silently where the isa field is null, but the pointer returned from myVersionString (and similar vars) is not null.

2. Getting the `_hostname` string once when creating the factory. As stated above I was not able to make it crash on the first instance.

Thank you for your time.

Edit: Just tested this in a macOS 13 VM on my machine and it also crashes the same way.

**Comment by baconpaul** [comment]
I wonder why at line 451 we have the comment not to release the bundle also

**Comment by baconpaul** [comment]
Also what an excellent bug report thank you.

im traveling this weekend mostly but will add these items to my dev list for next week!

**Comment by directmusic** [comment]
> I wonder why at line 451 we have the comment not to release the bundle also

I tried releasing it while I was testing and I am not 100% sure off the top of my head, but believe it simply crashed when inserting the second instance when calling CFBundleGetMainBundle().

**Comment by directmusic** [comment]
I was scanning through the docs on [Core Foundation](https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFMemoryMgmt/Concepts/Ownership.html#//apple_re%E2%94%82) and noticed that "The Get Rule" says that anytime a function references Get in Core Foundation we do not own it, it does not increase its reference count, and should not CFRelease it

I created a pull to follow that rule as this fixes the crash for me. This rule also explains why I was getting a strange crash while macOS was creating a crash report a few times. I assume they may call one of these functions to get some information about the executable but that data seems to be loaded at launch and expected to exist until close.
