### ISSUE TITLE
MIDI CCs being received on channel 16

### ISSUE THREAD

**Issue by tas-from-planet-u-he** [free-audio/clap-wrapper#32]
Tested on macOS Monterey 12.6.1 with a 2020 M1 Silicon MacBook Pro using Bitwig 4.4.2.

It seems that all MIDI CC messages sent on any MIDI channel somehow end up in the wrapped plugin with MIDI channel 16 assigned.

Note from David:
The underlying problem is that the MIDI CC1 (ModWheel) is being sent on channel 16.
It appears to be a bug in the wrapper because Bitwig does send a ch1 CC1 correctly to our own VST3. The wrapper performs a lookup from ID to parameter index and the returned parameter happens to be on channel 16 (0x0f).

There are a number of issues, likely caused by this:

* MIDI CCs are reaching the plugin on MIDI channel 16 instead of the correct channel
* in Hive, pitch bend and mod wheel are not working correctly
* in Repro, mod wheel does seem to work ok, only pitch bend has issues
* Aftertouch and Ctrl A+B feature not working in Repro and Hive
* Aftertouch and Ctrl A+B feature working ok in Zebra2

Ctrl A+B are simply two user defined MIDI CCs that can be used to modulate parameters via the plugin's mod matrix.

Pitch bend (PB) and mod wheel (MW) behaviour issue:

Using the mouse to adjust the graphical representation of pitch bend and md wheel works, the GUI elements move and the sound changes.
Using the real physical PB and MW on the NI Komplete keyboard does not work correctly.
The graphical MW does move in the GUI, but the sound does not change in Hive (this works ok in Repro).
The graphical PB jumps to its lowest position and stays there, the sound does not change (same in Hive and Repro).

**Comment by defiantnerd** [comment]
fixed in `next`

**Comment by tas-from-planet-u-he** [comment]
Tested with current "next" branch.
Tested with Hive 2 on M1 Mac with Monterey in Bitwig 4.4.3.

Mod wheel now working as expected.
Ctrl A&B Feature working.
Aftertouch is working.
Sustain pedal working.
MIDI CC assignment is using the correct MIDI channel.

There is still the issue with the pitch wheel, created a separate ticket for that, issue #37.
