### ISSUE TITLE
MIDI program changes not working

### ISSUE THREAD

**Issue by tas-from-planet-u-he** [free-audio/clap-wrapper#33]
Tested on macOS Monterey 12.6.1 with a 2020 M1 Silicon MacBook Pro using Bitwig 4.4.2.
Tested with multiple u-he plugins.

MIDI bank change messages are arriving at the wrapped plugin.

But program changes don't seem to enter the plugin at all.
Not even the plugin's MIDI activity led is reating.

Maybe this is related to the other MIDI issue (CC data being received on channel 16)?

**Comment by defiantnerd** [comment]
This is not related to #32.

**Comment by baconpaul** [comment]
Doesn’t vst3 turn program changes into internal patch list traversals? I thought program change and vst3 rarely worked

**Comment by defiantnerd** [comment]
merged to 0.8.0
