### ISSUE TITLE
Problems when reloading host projects

### ISSUE THREAD

**Issue by tas-from-planet-u-he** [free-audio/clap-wrapper#35]
Tested on macOS Monterey 12.6.1 with a 2020 M1 Silicon MacBook Pro using Bitwig 4.4.2 and with a Reaper development beta. Tested using Hive 2.

Reloading a project saved using the wrapped version of a plugin loads the project just fine, as long as the wrapped plugin is in place.

If the wrapped version is removed and replaced with the real VST3 version, the project won't find the plugin.

And trying to load a new VST3 instance inside of this project does not work at first (only tested in Bitwig).
You first have to load a VST2 or CLAP instance of this plugin into the project. Then you can suddenly load the VST3 version as well.

The same is true if you try to reload a project created with the real VST3 version after replacing it with the wrapped version.

**Comment by defiantnerd** [comment]
To replace already shipped VST3 plugins, the CLAP needs to implement the CLAP_PLUGIN_AS_VST3 extension (see https://github.com/free-audio/clap-wrapper/blob/main/include/clapwrapper/vst3.h) to provide a GUID of the previously shipped VST3 plugin.

By default, the GUID is being calculated from the ID in the CLAP plugin description, which is completely sufficient for new or clap-only plugins.

**Comment by tas-from-planet-u-he** [comment]
We implemented this extension.
It now works mostly, a project created with the real version can be reloaded using the wrapped version, in Reaper and Bitwig.

However, a project created with the wrapped version can only be reloaded with the real VST3 in Reaper.
This doesn't work in Bitwig, it still cannot load the real VST3 plugin because it fails to load the plugin state.
