### ISSUE TITLE
Sound not correct after loading init preset

### ISSUE THREAD

**Issue by tas-from-planet-u-he** [free-audio/clap-wrapper#38]
Tested using the current "next" branch. (was testing the fix for issue #32)
Tested with Hive 2 on M1 Mac with Monterey in Bitwig 4.4.3.

When loading the init preset, not all parameters are set to the correct values.

Example using Hive:

* load preset "Detuned Punk" (preset doesn't really matter, but sound issue is quite obvious with that one)
* now right-click on Hive's main data display and choose "Init"
* play a note, sounds wrong
* choose the Init preset once more, now the sound will be correct

**Comment by baconpaul** [comment]
i wonder if you have parameters with the id bit set > 2^31? We fixed that a week or so ago and it might cause what you mention.

**Comment by defiantnerd** [comment]
> i wonder if you have parameters with the id bit set > 2^31? We fixed that a week or so ago and it might cause what you mention.

I've checked that, all is correct. I suspect that this has been solved for now - feel free to re open, when it can be replicated.

**Comment by tas-from-planet-u-he** [comment]
Did some tests and this seems to be fixed indeed. Thanks a bunch.
