### ISSUE TITLE
Windows Clang: Make it work and add to CI

### ISSUE THREAD

**Issue by baconpaul** [free-audio/clap-wrapper#74]
Topic says it all

The trick ys

`cmake (blah) -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang`

**Comment by baconpaul** [comment]
So I tried this (see https://github.com/free-audio/clap-wrapper/pull/79)

short version

1. with llvm clang++ gnu like extensions, vst3 spits masses of warnings and errors
2. with clang-cl and ninja a bunch of earlier errors occur with MT and the like

So my conclusion is: windows clang isn't working now.

**Comment by baconpaul** [comment]
OK so as of now

Windows g++ builds with Werror in CI with a couple of -Wno-blah in place
Clang builds in CI but we turn off Werror altogether. We need to review the CI errors and see if we can fix or -Wno- them away.

But I'm going to mark this one solved in next since it does build.

**Comment by defiantnerd** [comment]
Merged to 0.6.0
