### ISSUE TITLE
A macOS self-contained wrapper strategy

### ISSUE THREAD

**Issue by baconpaul** [free-audio/clap-wrapper#78]
There's a bunch of ways you can make a 'self contained' VST3 or AUV2 or what not with a clap, but I think the cleanest and most-macOS-friendly way is as follows

1. Build the wrapper
2. After assembling the wrapper but before signing, copy the foo.clap to foo.vst3/~~Frameworks~~PlugIns/foo.clap
3. Modify the clap load path on macOS to check local frameworks first

and, in theory, voila.

This doesn't preclude the lookup-installed strategy but it may make it more robust under partial installs or "delete the bits I dont use" user actions.

**Comment by baconpaul** [comment]
#88 accomplishes this.

**Comment by defiantnerd** [comment]
just as an idea: we could scan all plugins in `foo.vst3/Plugins/*.clap` and allow them in one package.
But this would of course require some changes in the wrapper because we would need to keep multiple libraries alive.
