### ISSUE TITLE
Ramp up compiler warnings

### ISSUE THREAD

**Issue by 0ax1** [free-audio/clap-wrapper#81]
As of now, the `clap-wrapper` target uses the default minimum of compiler warnings. In order to catch as many errors as possible at compile time, additional warning groups such as `-Wall`, `-Wextra` and `-Wpedantic` should be considered.

After resolving all warnings for the added groups, we could think about enabling warnings as errors: `-Werror`.

**Comment by 0ax1** [comment]
landed for clang/gcc in: https://github.com/free-audio/clap-wrapper/pull/109

**Comment by baconpaul** [comment]
we are now `-Wall -Wextra -Wpedantic -Werror` on gcc and clang. Thanks for raising this.

I suggest we open a separate issue for MSVC and close this one when we make 0.5.0
