### ISSUE TITLE
How to build the auv2 info plist

### ISSUE THREAD

**Issue by baconpaul** [free-audio/clap-wrapper#92]
the list of plugins is in the auv2 info plist along with their entry points. this means you need to run the clap

a convo @defiantnerd and I had on discord outlined strategy as:

- have a little cmake build time utility which loads your clap and asks for your descriptions
- in cmake you specify the manufacturer code
- we use the "first feature" (instrument, effect, note effect) to pick the type (aumu aufx aumi)
- we use a hash of the id to 4 chars to produce the au code, or allow you to explicitly specify it as a list in cmake if you prefer
and then voila

**Comment by baconpaul** [comment]
this is now in next! yay!

**Comment by defiantnerd** [comment]
Merged to 0.6.0
